version: '3.8'
services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile 
    image: leftover-express.local
    container_name: leftover-express.local
    ports:
      - '8080:8080'
    volumes:
      - ./back-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  access-maps:
    build: 
      context: ./access-maps
      dockerfile: Dockerfile
    image: leftover-react.local
    container_name: leftover-react.local
    ports:
      - '3000:3000'
    volumes:
      - ./access-maps:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
